// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDKhV7QEsFpsPwDlklUY8JHf86RM-3SFg',
    appId: '1:5212232142:web:481dbb84fb062bc8ee339f',
    messagingSenderId: '5212232142',
    projectId: 'storeapp-cb6bc',
    authDomain: 'storeapp-cb6bc.firebaseapp.com',
    storageBucket: 'storeapp-cb6bc.appspot.com',
    measurementId: 'G-NR8TMMD69D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuqh5ZYQrQOQhdBp8JVadRgr1KMLExnZ0',
    appId: '1:5212232142:android:9ccd5a52a5ddc2b1ee339f',
    messagingSenderId: '5212232142',
    projectId: 'storeapp-cb6bc',
    storageBucket: 'storeapp-cb6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVyPNkiTFcAq1WarEH19fFOAuFnVqZfCo',
    appId: '1:5212232142:ios:fb9960d553201d10ee339f',
    messagingSenderId: '5212232142',
    projectId: 'storeapp-cb6bc',
    storageBucket: 'storeapp-cb6bc.appspot.com',
    iosBundleId: 'com.example.storeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDKhV7QEsFpsPwDlklUY8JHf86RM-3SFg',
    appId: '1:5212232142:web:af3c2b955d4fc38dee339f',
    messagingSenderId: '5212232142',
    projectId: 'storeapp-cb6bc',
    authDomain: 'storeapp-cb6bc.firebaseapp.com',
    storageBucket: 'storeapp-cb6bc.appspot.com',
    measurementId: 'G-SWGZ3588NV',
  );
}
